version: '3.8'

networks:
  nats-network:


services:
  nats-server:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    # command: --cluser_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222
    networks:
      - nats-network
